### ISSUE TITLE
"compilecmp" reports binary size is increased while it does not.

### ISSUE THREAD

**Issue by cuonglm** [josharian/compilecmp#3]
I run `compilecmp` against my patch to compiler. `compilecmp` reports that the `compile` binary size is increased, but `size` reports it doesn't.

```
$ cat size_before
__TEXT __DATA __OBJC others dec hex
17698816 962376 0 17567784 36228976 228cf70
$ cat size_after
__TEXT __DATA __OBJC others dec hex
17694720 962376 0 17567672 36224768 228bf00
```

`size_*` files are created by running `size $(go tool -n compile) >file`.

What `compilecmp` reports:

```
file    before    after     Δ       %
compile 24096808  24104888  +8080   +0.034%
vet     8223776   8219680   -4096   -0.050%
total   131801124 131805108 +3984   +0.003%
```

**Comment by josharian** [comment]
I wonder whether we are measuring different things.

`compilecmp` measures the size of binaries generated by running `make.bash`. That means that it measures the compiler as compiled by itself. (As opposed to the compiler as compiled by two different compilers, before and after.)

You write that you are running: `size $(go tool -n compile) >file`. It'd be helpful to see the entire transcript, because otherwise it is unclear what file `$(go tool -n compile)` actually returns.

**Comment by cuonglm** [comment]
Hi @josharian, `go tool -n compile` points to the `compile` binary after running `make.bash`, example in my darwin, it's `/Users/cuonglm/sources/go/pkg/tool/darwin_amd64/compile`. To clarify, what steps I did:

 - Checkout master
 - Run make.bash
 - Run `size $(go tool -n compile) >size_before`
 - Apply my patch
 - Run make.bash
 - Run `size $(go tool -n compile) >size_after`
 - Run `compilecmp`

**Comment by josharian** [comment]
What CL? So I can try to reproduce.

**Comment by cuonglm** [comment]
> What CL? So I can try to reproduce.

It's freeze time now, so I haven't send the CL yet. I included the patch in attached file.

[rangerdanger.patch.txt](https://github.com/josharian/compilecmp/files/3807191/rangerdanger.patch.txt)

**Comment by josharian** [comment]
I tried to reproduce and couldn't.

compilecmp:

```
$ compilecmp -n 0 -obj
13:48:17 compilecmp   master   HEAD
13:48:17 master: runtime/cgo: add -Wno-nullability-completeness on Darwin
13:48:17 HEAD: apply patch from cuong
13:48:17 cp <master> /Users/josh/.compilecmp/fb37821014fae9fe849689a900049361158111f0
13:48:19 /Users/josh/.compilecmp/fb37821014fae9fe849689a900049361158111f0/src/make.bash
13:49:49 cp <HEAD> /Users/josh/.compilecmp/4f0a8f0caabce9f92c4ba049849748783aaf6aae
13:49:50 /Users/josh/.compilecmp/4f0a8f0caabce9f92c4ba049849748783aaf6aae/src/make.bash
13:51:24 before: /Users/josh/.compilecmp/fb37821014fae9fe849689a900049361158111f0
13:51:24 after: /Users/josh/.compilecmp/4f0a8f0caabce9f92c4ba049849748783aaf6aae

file    before    after     Δ       %       
compile 24164288  24164176  -112    -0.000% 
total   132236780 132236668 -112    -0.000% 

file                      before    after     Δ       %       
cmd/compile/internal/gc.a 8931370   8924956   -6414   -0.072% 
total                     130166752 130160338 -6414   -0.005% 
```

size before:

```
$ ls -l $(go tool -n compile)
-rwxr-xr-x  1 josh  staff  24135616 Nov  6 14:00 /Users/josh/go/tip/pkg/tool/darwin_amd64/compile
$ size $(go tool -n compile)
__TEXT	__DATA	__OBJC	others	dec	hex
17739776	964904	0	17569728	36274408	22980e8
```

size after:

```
$ ls -l $(go tool -n compile)
-rwxr-xr-x  1 josh  staff  24135504 Nov  6 13:55 /Users/josh/go/tip/pkg/tool/darwin_amd64/compile
$ size $(go tool -n compile)
__TEXT	__DATA	__OBJC	others	dec	hex
17735680	964904	0	17569616	36270200	2297078
```

Note also that compilecmp uses stat to show the actual file size on disk. size shows the sizes of segments. It is not unimaginable that they might disagree, e.g. due to alignment constraints.

**Comment by cuonglm** [comment]
Hi @josharian, I use `compilecmp -n 15` without `-obj`, is it different?

**Comment by josharian** [comment]
`-obj` causes compilecmp to print size information about all object files. It is helpful because it offers a finer-grained look at which packages are impacted by a change, and how much. (Binary size changes are much coarser-grained. They're included by default since they're what users actually see, and because there are much fewer of them than object files.)

**Comment by josharian** [comment]
`-n 0` is useful if you just want to see size info, because it is much faster. (The compiler is deterministic.)

**Comment by cuonglm** [comment]
Hi @josharian, I run `compilecmp -n0 -obj`, the result:

```
07:36:08 compilecmp   master   HEAD
07:36:08 master: runtime: mark testSetPanicOnFault as go:nocheckptr
07:36:08 HEAD: cmd/compile: avoid range over copy of array
07:36:08 cp <master> /Users/cuonglm/.compilecmp/6ce4384fd6621454a1d58a4ab46f92da8d8567ed
07:36:09 /Users/cuonglm/.compilecmp/6ce4384fd6621454a1d58a4ab46f92da8d8567ed/src/make.bash
07:36:59 cp <HEAD> /Users/cuonglm/.compilecmp/df5d6760f20af555e9b4a86db0ed61151568b412
07:37:01 /Users/cuonglm/.compilecmp/df5d6760f20af555e9b4a86db0ed61151568b412/src/make.bash
07:37:51 before: /Users/cuonglm/.compilecmp/6ce4384fd6621454a1d58a4ab46f92da8d8567ed
07:37:51 after: /Users/cuonglm/.compilecmp/df5d6760f20af555e9b4a86db0ed61151568b412

file    before    after     Δ       %
compile 24168384  24164176  -4208   -0.017%
pack    2227336   2231432   +4096   +0.184%
total   132333852 132333740 -112    -0.000%

file                      before    after     Δ       %
cmd/compile/internal/gc.a 8931606   8925192   -6414   -0.072%
total                     130253858 130247444 -6414   -0.005%
```

So looks identical with yours, except the `pack`.

**Comment by josharian** [comment]
Maybe you're using a different base commit.

Do you still think there's a bug here?

**Comment by cuonglm** [comment]
> Maybe you're using a different base commit.
> 
> Do you still think there's a bug here?

I think no, as the report is now look the same with `size`, I land the CL https://go-review.googlesource.com/c/go/+/205777

Could you please try with current master, to see if `pack` appears in your result as well.

**Comment by josharian** [comment]
> Could you please try with current master, to see if pack appears in your result as well.

It doesn't. But I'm not convinced it is a good use of time to track down why. Are you running linux? There could be other reasons as well.

**Comment by cuonglm** [comment]
> > Could you please try with current master, to see if pack appears in your result as well.
> 
> It doesn't. But I'm not convinced it is a good use of time to track down why. Are you running linux? There could be other reasons as well.

I ran above command in my Mac, but I have a Linux laptop as well. I know you use Mac as well, that's why I wonder the difference between mine and yours.

Anyway, thanks for taking time for this.
