### ISSUE TITLE
dumpssa: print out CFG by default

### ISSUE THREAD

**Issue by erifan** [josharian/compilecmp#8]
This is a small change, but very useful.
```
diff --git a/dumpssa.go b/dumpssa.go
index ce86358..bd23e75 100644
--- a/dumpssa.go
+++ b/dumpssa.go
@@ -41,7 +41,7 @@ func dumpSSA(platform string, before, after commit, fnname string) {
                }
                cmd := exec.Command(cmdgo, args...)
                goos, goarch := parsePlatform(platform)
-               cmd.Env = append(os.Environ(), "GOOS="+goos, "GOARCH="+goarch, "GOSSAFUNC="+fnname)
+               cmd.Env = append(os.Environ(), "GOOS="+goos, "GOARCH="+goarch, "GOSSAFUNC="+fnname+":*")
                cmd.Dir = filepath.Join(c.dir, "src")
                pipe, err := cmd.StderrPipe()
                check(err)

```

**Comment by josharian** [comment]
It’s super useful when you’re working on CFG stuff. But it gets in the way when working on other things. What I have been doing is appending the `:*` to the func name when I invoke it, which works. I’d be open to adding a flag for this, if you’d like, but I don’t think it should be on by default.

**Comment by erifan** [comment]
> What I have been doing is appending the `:*` to the func name when I invoke it, which works. 

Oh yes, this is a good way, and it is more flexible, thanks. I think we can close this issue now.
