### ISSUE TITLE
Readme: improve description on benchmark test

### ISSUE THREAD

**Issue by erifan** [josharian/compilecmp#9]
Regarding the number of runs, I initially thought it would only work when I specified a specific benchmark. In fact, when we specify the number of runs, all benchmarks will be run by default.  This is best explained in this section. 

When we do not specify the number of runs but the -all or -pkg option, the performance test does not seem to be executed ? At least I didn't see any benchmark or allocation data being printed.

We can understand these points through some exploration, but if it can be marked in the document, it should help novices to understand and use this tool faster.

**Comment by josharian** [comment]
Excellent points, thanks. Will fix.
